### ISSUE TITLE
Specific character length when shipping?

### ISSUE THREAD

**Issue by Stiesel** [ioBroker/ioBroker.whatsapp-cmb#12]
**Versions:**  
 - Adapter version:  0.1.6
- Node.js v12.22.6
- NPM v6.14.15
- Pi OS v5.10

Hello, unfortunately, when sending via Blockly the messages are shortened if they are sent via WhatsApp, but if I use the Telegram adapter all characters are transmitted.

**Comment by Apollon77** [comment]
If you know the limit then please tell and I can add it to the readme ... else contact callmebot for details
