### ISSUE TITLE
Phone number in ioBroker seems to be outdated

### ISSUE THREAD

**Issue by PastCoder** [ioBroker/ioBroker.whatsapp-cmb#13]
**Describe the bug**  
On page http://<iobroker instance>/tab-adapters/readme/whatsapp-cmb there is a different phone number liste (which does notz work) compared to https://www.callmebot.com/blog/free-api-whatsapp-messages/

**Versions:**  
 - Page used on 11-Sept-2021

**Comment by Apollon77** [comment]
updated readme, thank you!
