### ISSUE TITLE
Issues when updating iobroker js-controller to 5.0.16

### ISSUE THREAD

**Issue by DaDue-max** [ioBroker/ioBroker.whatsapp-cmb#130]
**Describe the bug**  
after updating the iobroker to js-controller 5.0.16 a list of errors messages continously filling up my log file. (see below)
Whatsapp-Adapter stays red in the adapter view.
If I stop the adapter, no error messages in the log file anymore.

**To Reproduce**  
update to 5.0.16., activate whatsapp-cmb adapter. check log file.

**Expected behavior**  
adapter should reflect status green without errors in the log file

**Screenshots & Logfiles**  
`<html><body>

host.iobroker | 2023-11-14 16:47:27.213 | warn | instance system.adapter.whatsapp-cmb.1 terminated due to SIGABRT
-- | -- | -- | --
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught by controller[21]: 21: 0x17035b9  [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[20]: 20: 0x12e1d40  v8::internal::Runtime_SetKeyedProperty(int, unsigned long*,  v8::internal::Isolate*) [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[19]: 19: 0x11b8076  v8::internal::Object::SetProperty(v8::internal::LookupIterator*,  v8::internal::Handle<v8::internal::Object>,  v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>)  [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[18]: 18: 0x11b7223  v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*,  v8::internal::Handle<v8::internal::Object>,  v8::internal::PropertyAttributes,  v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin,  v8::internal::EnforceDefineSemantics) [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[17]: 17: 0x119eef2  v8::internal::Object::TransitionAndWriteDataProperty(v8::internal::LookupIterator*,  v8::internal::Handle<v8::internal::Object>,  v8::internal::PropertyAttributes,  v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin)  [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[16]: 16: 0x1181122  v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSReceiver>,  v8::internal::Handle<v8::internal::Object>,  v8::internal::PropertyAttributes, v8::internal::StoreOrigin)  [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[15]: 15: 0x1193367  v8::internal::Map::TransitionToDataProperty(v8::internal::Isolate*,  v8::internal::Handle<v8::internal::Map>,  v8::internal::Handle<v8::internal::Name>,  v8::internal::Handle<v8::internal::Object>,  v8::internal::PropertyAttributes, v8::internal::PropertyConstness,  v8::internal::StoreOrigin) [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[14]: 14: 0x11916b4  v8::internal::Map::CopyWithField(v8::internal::Isolate*,  v8::internal::Handle<v8::internal::Map>,  v8::internal::Handle<v8::internal::Name>,  v8::internal::Handle<v8::internal::FieldType>,  v8::internal::PropertyAttributes, v8::internal::PropertyConstness,  v8::internal::Representation, v8::internal::TransitionFlag)  [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[13]: 13: 0x119119b  v8::internal::Map::CopyAddDescriptor(v8::internal::Isolate*,  v8::internal::Handle<v8::internal::Map>,  v8::internal::Descriptor*, v8::internal::TransitionFlag) [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[12]: 12: 0x11a4eb7  v8::internal::DescriptorArray::CopyUpTo(v8::internal::Isolate*,  v8::internal::Handle<v8::internal::DescriptorArray>, int, int)  [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[11]: 11: 0xf0a762  v8::internal::FactoryBase<v8::internal::Factory>::NewDescriptorArray(int,  int, v8::internal::AllocationType) [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[10]: 10: 0xf081d4  v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int,  v8::internal::AllocationType, v8::internal::Map,  v8::internal::AllocationAlignment) [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[9]:  9: 0xf10760 v8::internal::Factory::AllocateRaw(int,  v8::internal::AllocationType, v8::internal::AllocationAlignment)  [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[8]:  8: 0xf30217  v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int,  v8::internal::AllocationType, v8::internal::AllocationOrigin,  v8::internal::AllocationAlignment) [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[7]:  7: 0xf2ee4e  v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int,  v8::internal::AllocationType, v8::internal::AllocationOrigin,  v8::internal::AllocationAlignment) [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[6]:  6: 0xf5474d  v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace,  v8::internal::GarbageCollectionReason, v8::GCCallbackFlags)  [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught by controller[5]:  5: 0xf42265  [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught  by controller[4]:  4: 0xd64b67  v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char  const*, bool) [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught by controller[3]:  3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.213 | error | Caught by controller[2]:  2: 0xa94834  [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.212 | error | Caught by controller[1]:  1: 0xb83f50 node::Abort() [/usr/bin/node]
host.iobroker | 2023-11-14 16:47:27.212 | error | Caught by controller[0]: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
host.iobroker | 2023-11-14 16:47:27.212 | error | Caught by controller[0]: <--- JS stacktrace --->
host.iobroker | 2023-11-14 16:47:27.212 | error | Caught  by controller[0]: em[4788:0x67623b0]      414 ms: Mark-sweep (reduce)  18.9 (21.2) -> 18.2 (20.9) MB, 4.7 / 0.0 ms  (+ 0.6 ms in 9 steps  since start of marking, biggest step 0.1 ms, walltime since start of  marking 11 ms) (average mu = 0.752, current mu = 0.574) finalize  incre[4788:0x67623b0]      424 ms: Mark-sweep (reduce) 19.4 (20.9) ->  18.9 (21.9) MB, 5.0 / 0.0 ms  (+ 1.1 ms in 15 steps since start of  marking, biggest step 0.1 ms, walltime since start of marking 9 ms)  (average mu = 0.623, current mu = 0.398) allocation fai
host.iobroker | 2023-11-14 16:47:27.212 | error | Caught by controller[0]: <--- Last few GCs --->

</body>
</html>`

**Versions:**  
 - Adapter version: 0.2.3
 - JS-Controller version: 5.0.16
 - Node version: 18.17.1
 - Operating system: debian 11.7 (in lxc container in proxmox (8.0.4)

**Comment by DaDue-max** [comment]
...additional comment on this: you get rid of these errors by deleting the adapter (and instances) and reinstalling it.....you may close the issue.

**Comment by Apollon77** [comment]
This is7was an out of memotry error ... but glad you solved the topic
