### ISSUE TITLE
Support other messengers

### ISSUE THREAD

**Issue by PastCoder** [ioBroker/ioBroker.whatsapp-cmb#14]
**Is your feature request related to a problem? Please describe.**
https://www.callmebot.com/blog/free-api-whatsapp-messages/ seems to support different messengers in the same way as Whatsapp. Would be great if the user could select in the ioBoraker adapter which messenger to use (e.g. Signal).

**Describe the solution you'd like**
Provide different functions or add a parameter to choose the messenger.

**Describe alternatives you've considered**
As far as I know there is no adapter for Signal yet, but some requests for it already.

**Additional context**
-

**Comment by Apollon77** [comment]
This is the whatsapp adapter :-) So it makes no sense to support more then whatsapp :-)

Pleas eOpen an Adapter Request or check existing Adapter requests at https://github.com/ioBroker/AdapterRequests/issues

**Comment by PastCoder** [comment]
Sure it is from the name. Technically I thought it could easily be extended. A related adapter requests exists: https://github.com/ioBroker/AdapterRequests/issues/527
I'll add a comment there, if this (technical) adapter could be extended (with adjusted name :-) )

**Comment by Apollon77** [comment]
> adapter could be extended (with adjusted name :-) )

and exactly the latter part is the proboematic one for all users that use the current one. SO better to have one adapter per communication way
