### ISSUE TITLE
Allow emojis

### ISSUE THREAD

**Issue by gaudes** [ioBroker/ioBroker.whatsapp-cmb#15]
**Is your feature request related to a problem? Please describe.**
To get a quick information which part of my smart home is affected from the message it would be great when emojis could be used.

**Describe the solution you'd like**
CallMeBot already supports this:
https://www.callmebot.com/uncategorized/how-to-use-emoticos-with-the-api/

Problem seems to be the encoding of the text.

Maybe there could be another state for already encoded text ? Then there could be entered the emoji with the text already encoded.

**Comment by Apollon77** [comment]
Please check GitHub version
