### ISSUE TITLE
No Messages Today

### ISSUE THREAD

**Issue by Chris9463773** [ioBroker/ioBroker.whatsapp-cmb#150]
The last message came at 00:02 in the Morning. 
Normally at 13:00 and 22:10 there must be a few more messages.
Nothing happened.
Protocoll says "send... "

**Comment by Apollon77** [comment]
Did you contact andchecked with the service provider?

**Comment by Chris9463773** [comment]
It works again. There were no messages for a day, then suddenly it started working again. 
No idea why

**Comment by Apollon77** [comment]
One more reason to check with the whatsapp servie provider

**Comment by Apollon77** [comment]
As seen in the readme the adapter just uses https://www.callmebot.com/blog/free-api-whatsapp-messages/ ... so this service is really sending the mesages and such. So when there was an issue please check with them

**Comment by Chris9463773** [comment]
Again...since 4.3. no Messages.

Checked the service provider:
"Your Account is Paused due to technical issues.
Please send the word "resume" to the bot to re-enable the service for your number.
Thank you and sorry for the inconvenience."

i have send "resume" and it works.

But why has it stopped? Any idea?

**Comment by Apollon77** [comment]
I think this question should be asked to the service provider?
