### ISSUE TITLE
Not all errors are reported when sending message

### ISSUE THREAD

**Issue by Sneak-L8** [ioBroker/ioBroker.whatsapp-cmb#153]
**Describe the bug**  
If your number gets paused for whatever reason, no error is shown when trying to send a message.

**To Reproduce**  
* Manually send "pause" to service via your cell phone.
* Try to send a message from ioBroker. The message is lagged as "sent", but no error is shown.
* (Manually send "resume" to service via your cell phone.)

**Expected behavior**  
I expect an error in log.

**Versions:**  
 - Adapter version: 0.2.3
 - JS-Controller version: 5.0.19
 - Node version: 18.19.0
 - Operating system: linux Raspi4B

**Additional context**  
Error codes from the API:
201 - wrong parameters
202 - your number is banned
203 - APikey is incorrect
209 - phone number is permanent banned
204 - Too many messages sent (API overflow for the phone number)
205 - Unknown error.
207 - Service is down
208 - Your number is in Pause.
209 - Quota exceeded
210 - Messaged queued to be sent later

**Comment by Sneak-L8** [comment]
@Apollon77 I fixed it and created and PR.

**Comment by Apollon77** [comment]
Thank you, will be in next version
