### ISSUE TITLE
V 0.2.1: special characters are not displayed correct, %-ASCII 

### ISSUE THREAD

**Issue by fila612** [ioBroker/ioBroker.whatsapp-cmb#19]
**Describe the bug**  
After Update to version 0.2.1 the Textmessages are displayed not correct. spaces and German Umlaute (like Ä,Ü,Ö,..) seems to be in a html eroding.

**To Reproduce**  
Nothing changed but I used the adapter to inform me via adapter device reminder. so before I run the update, the text was correct.
1. start e.g. washing Maschine
2. text message via device reminder to whatsapp is sendet
3. check text message
4. used Text: "Waschmaschine wurde gestartet"

**Expected behavior**  
Text are displayed as configured, "Waschmaschine wurde gestartet"

**Observed  behavior** 
"Waschmaschine%20wurde%20gestartet"

**Screenshots & Logfiles**  
![Bildschirmfoto 2022-03-27 um 07 24 58](https://user-images.githubusercontent.com/29542374/160268034-35eb26c3-588c-4846-93a5-b96cae486ee7.png)

**Versions:**  
 - Adapter version: 0.2.1
 - JS-Controller version: 4.0.21
 - Node version: 14.19.0
 - Operating system: ubuntu 21.10 (proxmox lxc)

**Additional context**  
in device reminder are 2 users configured (my wife and me), but my wife uses telegram. the text is for sending via WhatsApp and telegram is set up onetime and both messenger adapters uses them. the Error occurs only in WhatsApp adapter, text in telegram are still fine.

**Comment by Apollon77** [comment]
Fixed on GitHub already ... 0.2.2 on it's way to github. repo update then later

Thank you for reporting
