### ISSUE TITLE
Agbs Whatsapp/ Rules from Whatsapp Company?

### ISSUE THREAD

**Issue by canim60** [ioBroker/ioBroker.whatsapp-cmb#2]
Hallo, stößt der Bot gegen die Abgs? Hab eher sorgen um mein Account bzw die Nr. Hat sich da einer schon schlau gemacht?

Hello,  i have a question. Do this Service against the rules from Whatsapp?,Im afraid of my account / Nummber.

**Comment by GermanBluefox** [comment]
Please ask here: https://www.callmebot.com/blog/free-api-whatsapp-messages/
