### ISSUE TITLE
Welche Telefonnummer?

### ISSUE THREAD

**Issue by actionbyte** [ioBroker/ioBroker.whatsapp-cmb#22]
Nummer unter der stable V0.1.6: +34 644 10 55 84
Nummer beta V 0.2.2: +34 698 28 89 73
Nummer  im [Github:](https://github.com/ioBroker/ioBroker.whatsapp-cmb): +34 644 44 21 48
Nummer unter [Callmebot.com](https://www.callmebot.com/blog/free-api-whatsapp-messages/): +34 644 91 07 79 

Ich habe an alle Nummern die Initialnachricht zur Aktivierung zum Apikey geschickt, leider bisher von keiner eine Antwort bekommen.
Welche ist aktuell bzw. korrekt?

**Comment by Apollon77** [comment]
An sich sollte immer die auf der callmebot seite aktuell sein. Wenn es nicht geht bitte erstmal dort melden und klären und gern hier Feedback geben.

So oft wie die die Nummer ändern können wir das gar nicht aktuell halten :-(

**Comment by actionbyte** [comment]
Danke! Die Nummer auf Callmebot.com ist die aktuelle.
Vielleicht noch wichtig zu erwähnen das zur Initialisierung vom API-Key nicht die englische Variante funktioniert.
Zumindest bei mir hat der Bot nur auf die deutsche Vorgabe "Ich erlaube callmebot mir nachrichten zu senden" reagiert.
