### ISSUE TITLE
I did not get an API

### ISSUE THREAD

**Issue by c6786** [ioBroker/ioBroker.whatsapp-cmb#23]
I tried 4 different numbers, found in the internet. No answer from the callmebot

**Comment by Apollon77** [comment]
Pleasde contact callmebot as the operator of the service! And please provide the solution here maybe we can add to Readme

**Comment by c6786** [comment]
Take the phone number from the website: https://www.callmebot.com/blog/free-api-whatsapp-messages/
Try it serveral times.

**Comment by x2on** [comment]
> Take the phone number from the website: https://www.callmebot.com/blog/free-api-whatsapp-messages/ Try it serveral times.

This number works. The original number from the README sends me an other number back, because it should be full. But this number doesn't work.

So +34 644 97 54 14 works at the moment

**Comment by Apollon77** [comment]
We now refer to webpage only
