### ISSUE TITLE
Sending pictures dont work for me

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.whatsapp-cmb#3]
First of all, thx for the adapter. 
I'm currently using the Telegram Adapter but actually just for iobroker. This is why I would like to switch to whatsap - my main messenger. When I ported my blockly to wcmb I relized that sending pictures (door bell) does not work currently.
Telegram adapter just accepts : "/opt/iobroker/iobroker-data/cam.snap.jpg" as txt while wcmb just sends the plain string :)

**Comment by GermanBluefox** [comment]
As far, as I know the sending of pictures is not possible. (At least for now)
