### ISSUE TITLE
Signal

### ISSUE THREAD

**Issue by Fritzelspitze** [ioBroker/ioBroker.whatsapp-cmb#6]
Vom gleichen Anbieter gibts auch Signal was ich mir ebenfalls als Dienst wünschen würde. Der URL Aufruf ist nur minimal anders. Da ich jetzt aber nicht einfach dein Projekt Forken will, nur um dann 10 Zeichen zu ändern, wäre es super, wenn du das selbst machst und als weiteres Projekt machst.

**Comment by Apollon77** [comment]
@Fritzelspitze Bitte unter AdapterRequests als issue anlegen, hier im Adapter ist es falsch
